includes:
  - base.yaml

model:
  model_name: GSATGNNs_MODIFIED

ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
  - 0.4    # K
  - 0.03   # epsilon
  - 1      # game_iterations
  - 0.005  # merlin_lr
  - 3      # morgana_steps
  - 0.01   # morgana_lr = epsilon / steps
  - 0.1    # morgana_weight

train:
  mile_stones:
    - 80

log_file: exp_balanced
clean_save: true
use_norm: none
mitigation_sampling: default