includes:
  - base.yaml

model:
  model_name: GSATGNNs_MODIFIED

ood:
  ood_alg: GSAT
  ood_param: 1.0
  extra_param:
    - 0.2        # K
    - 0.005     # epsilon
    - 2         # game_iterations
    - 0.001    # merlin_lr
    - 2         # morgana_steps
    - 0.0001    # morgana_lr
    - 0.1      # morgana_weight

train:
  mile_stones:
    - 200

log_file: exp_balanced
clean_save: true
use_norm: none
mitigation_sampling: default